name: Maven central workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn test | tee out
      #- run: mvn --update-snapshots clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report | tee out
        shell: bash
      - run: tail -1000 out
