name: Maven central workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maven:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [APITests
          ,ActiveUserTests
          ,ActualCostRecordMapperTest
          ,AddInfoAPITests
          ,AgedToLostScheduledNoticesProcessingTests
          ,AllowedServicePointsAPITests
          ,AnonymizeLoansAfterXIntervalTests
          ,AnonymizeLoansByUserIdAPITests
          ,AnonymizeLoansImmediatelyAPITests
          ,AnonymizeLoansNeverTests
          ,AnonymizeLoansRepresentationTest
          ,AnonymizeLoansTests
          ,AnonymizeRequestTests
          ,AnonymizeStorageRequestsRepositoryTest
          ,AnonymousWebContextTest
          ,AsyncCoordinationUtilTest
          ,AsynchronousResultCreationTests
          ,AsynchronousResultFlatMapFutureTests
          ,AsynchronousResultMapTests
          ,AsynchronousResultSideEffectTests
          ,BranchMappingFunctionsTests
          ,CalendarRepositoryTest
          ,CancelRequestTests
          ,ChangeDueDateAPITests
          ,ChangeDueDateByReplacingLoanTests
          ,ChangeDueDateValidatorTest
          ,CheckInAgedToLostItemTest
          ,CheckInByBarcodeTests
          ,CheckInByReplacingLoanTests
          ,CheckInDeclaredLostItemTest
          ,CheckInValidatorsTests
          ,CheckInWithdrawnItemTest
          ,CheckOutByBarcodeDryRunTests
          ,CheckOutByBarcodeFixedDueDateScenariosTest
          ,CheckOutByBarcodeTests
          ,CheckOutCalculateDueDateShortTermTests
          ,CheckOutCalculateDueDateTests
          ,CheckOutCalculateOffsetTimeTests
          ,CheckoutWithRequestScenarioTests
          ,CirculationPolicyRepositoryTest
          ,CirculationRulesAPITests
          ,CirculationRulesCacheTest
          ,CirculationRulesEngineAPITests
          ,CirculationSettingsServiceTest
          ,CirculationSettingsTests
          ,ClaimItemReturnedAPITests
          ,ClockUtilTests
          ,CloseAgedToLostLoanWhenLostItemFeesAreClosedApiTests
          ,CloseDeclaredLostLoanWhenLostItemFeesAreClosedApiTests
          ,ClosedRequestTests
          ,ContentTypeTest
          ,CqlQueryTests
          ,DateAndTimeJsonPropertyFetcherTests
          ,DateFormatUtilTests
          ,DateTimeUtilTests
          ,DeclareClaimedReturnedItemAsMissingApiTests
          ,DeclareLostAPITests
          ,DeferFailureErrorHandlerTest
          ,DetermineClosedLibraryStrategyForHoldShelfExpirationDateTests
          ,DetermineClosedLibraryStrategyTest
          ,DueDateNotRealTimeScheduledNoticesProcessingTests
          ,DueDateScheduledNoticesProcessingTests
          ,DueDateScheduledNoticesTests
          ,EndExpiredPatronActionSessionTests
          ,EnvironmentTest
          ,EventConsumerVerticleTest
          ,EventPublisherTest
          ,ExpiredActualCostRecordsProcessingTests
          ,FailFastErrorHandlerTest
          ,FakeCQLToJSONInterpreterSearchingTests
          ,FakeCQLToJSONInterpreterSortingTests
          ,FeeFineFacadeTest
          ,FindMultipleRecordsByIdTests
          ,FindMultipleRecordsUsingCqlTests
          ,FixedDueDateSchedulesTests
          ,FixedLoanPolicyCheckOutDueDateCalculationTests
          ,FixedLoanPolicyRenewalDueDateCalculationTests
          ,FixedScheduleCheckOutDueDateStrategyTest
          ,FixedScheduleRenewalDueDateStrategyTest
          ,FloatingItemsTests
          ,GeneralNoteTypeValidatorTests
          ,HealthServiceTest
          ,HoldShelfClearanceReportTests
          ,HoldShelfExpirationDateTests
          ,HoldShelfFulfillmentTests
          ,HoldingsRepositoryTest
          ,IdentityMapTests
          ,InHouseUseCheckInTest
          ,InTransitToHomeLocationTests
          ,InactiveUserValidatorTests
          ,InstanceRequestItemsComparerTests
          ,InstanceRequestsAPICreationTests
          ,InstanceTests
          ,IntervalTests
          ,InvalidLoanPolicyTests
          ,ItemLastCheckInTests
          ,ItemPermanentLocationTest
          ,ItemRepositoryTests
          ,ItemStatusApiTests
          ,ItemStatusValidatorTest
          ,ItemTests
          ,ItemsByInstanceResourceTest
          ,ItemsInTransitReportTests
          ,JsonArrayToStreamMapperTests
          ,JsonObjectArrayPropertyFetcherTests
          ,JsonPropertyFetcherTests
          ,JsonPropertyWriterTest
          ,JsonSchemaValidationTest
          ,JsonStringArrayPropertyFetcherTests
          ,KeepCurrentStrategyTest
          ,LauncherTest
          ,LibraryTimetableConverterTest
          ,LoanAPILocationTests
          ,LoanAPIProxyTests
          ,LoanAPIRelatedRecordsTests
          ,LoanAPITests
          ,LoanAPITitleTests
          ,LoanAnonymizationServiceTests
          ,LoanAnonymizationTests
          ,LoanCheckInServiceTest
          ,LoanDueDatesAfterRecallTests
          ,LoanLostDateTest
          ,LoanPolicyTest
          ,LoanTest
          ,LoanToChargeFeesTest
          ,LoansForUseAtLocationTests
          ,LocationRepositoryTest
          ,LogCheckInServiceTest
          ,LogMessageSanitizerTests
          ,LogUtilTest
          ,LostItemPolicyTest
          ,MappingFunctionsTests
          ,MoreThanOneLoanValidatorTests
          ,MoveRequestPolicyTests
          ,MoveRequestTests
          ,MultipleHoldShelfRequestsTests
          ,MultipleMixedFulfilmentRequestsTests
          ,MultipleOutOfOrderRequestsTests
          ,MultipleRecordsTests
          ,NameConverterTest
          ,NoLoanValidatorTests
          ,OffsetTest
          ,OkapiPermissionsTest
          ,OpeningDayTest
          ,OverdueFinePolicyTest
          ,OverdueFineScheduledNoticesProcessingTests
          ,OverdueFineServiceTest
          ,OverduePeriodCalculatorServiceTest
          ,OverrideRenewAgedToLostItemTest
          ,OverrideRenewByBarcodeTests
          ,OverrideRenewDeclaredLostItemTest
          ,OverrideRenewalTest
          ,PageRequestWorkflowTests
          ,PageableFetcherTest
          ,PatronActionSessionTests
          ,PatronSessionRecordTest
          ,PeriodTest
          ,PrintEventsTests
          ,ProxyRelationshipTests
          ,RecallItemsTests
          ,RegularRenewalTest
          ,ReminderFeeTests
          ,RenewByBarcodeRequestTests
          ,RenewByBarcodeTests
          ,RenewByIdRequestTests
          ,RenewByIdTests
          ,RenewalAPITests
          ,RenewalOfItemsWithReminderFeesValidatorTest
          ,RenewalValidatorTest
          ,RequestAnonymizationApiTests
          ,RequestAnonymizationRecordsTest
          ,RequestAnonymizationResourceTests
          ,RequestAnonymizationServiceTest
          ,RequestAnonymizationSettingsRepositoryTest
          ,RequestAnonymizationSettingsTest
          ,RequestByInstanceIdRequestTests
          ,RequestByInstanceIdResourceTests
          ,RequestByInstanceIdResourceTests
          ,RequestNoticeSenderTest
          ,RequestPolicyRepositoryTest
          ,RequestPolicyTests
          ,RequestQueueRemoveRequestTests
          ,RequestQueueResourceTest
          ,RequestQueueTests
          ,RequestQueueTests
          ,RequestRepositoryTest
          ,RequestRepresentationTests
          ,RequestScheduledNoticesProcessingTests
          ,RequestScheduledNoticesTests
          ,RequestStatusTest
          ,RequestTypeItemStatusWhiteListTests
          ,RequestsAPICreateMultipleRequestsTests
          ,RequestsAPICreationTests
          ,RequestsAPIDeletionTests
          ,RequestsAPILoanHistoryTests
          ,RequestsAPILoanRenewalTests
          ,RequestsAPILocationTests
          ,RequestsAPIProxyTests
          ,RequestsAPIRelatedRecordsTests
          ,RequestsAPIRetrievalTests
          ,RequestsAPITitleTests
          ,RequestsAPIUpdatingTests
          ,RequestsForDifferentItemsTests
          ,RequestsServicePointsTests
          ,ResponseInterpretationTests
          ,ResultAfterTests
          ,ResultApplySideEffectTests
          ,ResultCombineAfterTests
          ,ResultFailAfterTests
          ,ResultFailWhenTests
          ,ResultFailureMappingTests
          ,ResultGetValueTests
          ,ResultInitialisationTests
          ,ResultMappingTests
          ,ResultNextTests
          ,ResultNextWhenTests
          ,RollingLoanPolicyCheckOutDueDateCalculationTests
          ,RollingLoanPolicyRenewalDueDateCalculationTests
          ,SafelyInitialiseAsynchronousResultTests
          ,ScheduledAgeToLostApiTest
          ,ScheduledAgeToLostFeeChargingApiTest
          ,ScheduledRequestAnonymizationProcessingResourceTest
          ,SearchSlipsTests
          ,ServicePointCheckInTests
          ,ServicePointCheckOutTests
          ,SettingsRepositoryTest
          ,SingleClosedRequestTests
          ,SingleOpenDeliveryRequestTests
          ,SingleOpenHoldShelfRequestTests
          ,SpringApiTest
          ,StaffSlipsTests
          ,StreamToListMappingTests
          ,StringUtilTests
          ,TenantActivationResourceTests
          ,Text2DroolsTest
          ,TimePeriodTest
          ,UnknownLoanPolicyProfileTests
          ,UpdateRequestQueueTest
          ,UserAddressTests
          ,UserTests
          ,VertxWebClientOkapiHttpClientTests]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn test -Dtest=${{ matrix.test }},HoldShelfExpirationDateTests
        shell: bash
